include: 
  - ./static/.well-known/microsoft-identity-association.json
  - ./static/.well-known
  - ./static

keep_files:
  - ./static/.well-known/microsoft-identity-association.json
  - ./static/.well-known
  - ./static

